swarm:
  topology:
    consul:
      url: http://consul:8500
  datasources:
    data-sources:
      demoDS:
        driver-name: postgresql
        connection-url: jdbc:postgresql://postgres:5432/demo
        user-name: demo_${service.name}
        password: demo_${service.name}